In [2]:
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age', 'sex', 'class', 'fare', 'survived']]

grouped = df.groupby(['class', 'sex'], observed=True)
gdf = grouped.agg(['mean', 'std'], numeric_only=True)
print(gdf)

print(gdf.index)

                     age                   fare             survived
                    mean        std        mean        std      mean       std
class  sex
First  female  34.611765  13.612052  106.125798  74.259988  0.968085  0.176716
       male    41.281386  15.139570   67.226127  77.548021  0.368852  0.484484
Second female  28.722973  12.872702   21.970121  10.891796  0.921053  0.271448
       male    30.740707  14.793894   19.741782  14.922235  0.157407  0.365882
Third  female  21.750000  12.729964   16.118810  11.690314  0.500000  0.501745
       male    26.507589  12.159514   12.661633  11.681696  0.135447  0.342694
MultiIndex([( 'First', 'female'),
            ( 'First',   'male'),
            ('Second', 'female'),
            ('Second',   'male'),
            ( 'Third', 'female'),
            ( 'Third',   'male')],
           names=['class', 'sex'])

In [3]:
arrays = [['a', 'a', 'b', 'b'], [1, 2, 1, 2]]
multi_index_arrays = pd.MultiIndex.from_arrays(arrays, names=('letter', 'number'))
multi_index_arrays

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           names=['letter', 'number'])

In [5]:
tuples = [
    ('a', 1), 
    ('a', 2), 
    ('b', 1), 
    ('b', 2)
    ]
multi_index_tuples = pd.MultiIndex.from_tuples(tuples, names=('letter', 'number'))
multi_index_tuples

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           names=['letter', 'number'])

In [6]:
letters = ['a', 'b']
numbers = [1, 2]
multi_index_product = pd.MultiIndex.from_product([letters, numbers],
names=('letter', 'number'))

multi_index_product

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           names=['letter', 'number'])

In [8]:
df = pd.DataFrame([['a', 1], ['b', 2], ['b', 1], ['b', 2]], columns=['letter', 'number'])
multi_index_frame = pd.MultiIndex.from_frame(df)
multi_index_frame

MultiIndex([('a', 1),
            ('b', 2),
            ('b', 1),
            ('b', 2)],
           names=['letter', 'number'])

In [9]:
multi_index_frame.get_level_values(0)

Index(['a', 'b', 'b', 'b'], dtype='object', name='letter')

In [10]:
multi_index_frame.get_level_values('letter')

Index(['a', 'b', 'b', 'b'], dtype='object', name='letter')

In [13]:
gdf.columns.levels

FrozenList([['age', 'fare', 'survived'], ['mean', 'std']])

In [15]:
gdf.columns.get_level_values(0)

Index(['age', 'age', 'fare', 'fare', 'survived', 'survived'], dtype='object')

In [17]:
gdf.columns.get_level_values(1)

Index(['mean', 'std', 'mean', 'std', 'mean', 'std'], dtype='object')

In [18]:
gdf['age']

                    mean        std
class  sex
First  female  34.611765  13.612052
       male    41.281386  15.139570
Second female  28.722973  12.872702
       male    30.740707  14.793894
Third  female  21.750000  12.729964
       male    26.507589  12.159514

In [ ]:
# age 변수와 평균값 데이터 선택
gdf['age', 'mean']

class   sex
First   female    34.611765
        male      41.281386
Second  female    28.722973
        male      30.740707
Third   female    21.750000
        male      26.507589
Name: (age, mean), dtype: float64

In [20]:
# age변수를 먼저 선택하고 다시 평균값 선택
gdf['age']['mean']

class   sex
First   female    34.611765
        male      41.281386
Second  female    28.722973
        male      30.740707
Third   female    21.750000
        male      26.507589
Name: mean, dtype: float64

In [21]:
gdf.loc['First']

              age                   fare             survived
             mean        std        mean        std      mean       std
sex
female  34.611765  13.612052  106.125798  74.259988  0.968085  0.176716
male    41.281386  15.139570   67.226127  77.548021  0.368852  0.484484

In [22]:
gdf.loc[('First', 'female')]

age       mean     34.611765
          std      13.612052
fare      mean    106.125798
          std      74.259988
survived  mean      0.968085
          std       0.176716
Name: (First, female), dtype: float64

In [25]:
gdf.loc[('First', 'female'), 'age']

mean    34.611765
std     13.612052
Name: (First, female), dtype: float64

In [26]:
gdf.loc[('First', 'female'), ('age', 'mean')]

np.float64(34.61176470588235)

In [27]:
gdf.loc[('First', 'female'), ('age', 'std'):('fare', 'mean')]

age   std      13.612052
fare  mean    106.125798
Name: (First, female), dtype: float64

In [28]:
male_class = gdf.xs('male', level='sex')
male_class

              age                  fare             survived
             mean        std       mean        std      mean       std
class
First   41.281386  15.139570  67.226127  77.548021  0.368852  0.484484
Second  30.740707  14.793894  19.741782  14.922235  0.157407  0.365882
Third   26.507589  12.159514  12.661633  11.681696  0.135447  0.342694

In [29]:
gdf.sort_index(level=0, ascending=False)

                     age                   fare             survived
                    mean        std        mean        std      mean       std
class  sex
Third  male    26.507589  12.159514   12.661633  11.681696  0.135447  0.342694
       female  21.750000  12.729964   16.118810  11.690314  0.500000  0.501745
Second male    30.740707  14.793894   19.741782  14.922235  0.157407  0.365882
       female  28.722973  12.872702   21.970121  10.891796  0.921053  0.271448
First  male    41.281386  15.139570   67.226127  77.548021  0.368852  0.484484
       female  34.611765  13.612052  106.125798  74.259988  0.968085  0.176716

In [30]:
gdf.sort_index(level='sex', ascending=False)

                     age                   fare             survived
                    mean        std        mean        std      mean       std
class  sex
Third  male    26.507589  12.159514   12.661633  11.681696  0.135447  0.342694
Second male    30.740707  14.793894   19.741782  14.922235  0.157407  0.365882
First  male    41.281386  15.139570   67.226127  77.548021  0.368852  0.484484
Third  female  21.750000  12.729964   16.118810  11.690314  0.500000  0.501745
Second female  28.722973  12.872702   21.970121  10.891796  0.921053  0.271448
First  female  34.611765  13.612052  106.125798  74.259988  0.968085  0.176716

In [31]:
gdf.sort_index(level=['sex', 'class'], ascending=[False, True])

                     age                   fare             survived
                    mean        std        mean        std      mean       std
class  sex
First  male    41.281386  15.139570   67.226127  77.548021  0.368852  0.484484
Second male    30.740707  14.793894   19.741782  14.922235  0.157407  0.365882
Third  male    26.507589  12.159514   12.661633  11.681696  0.135447  0.342694
First  female  34.611765  13.612052  106.125798  74.259988  0.968085  0.176716
Second female  28.722973  12.872702   21.970121  10.891796  0.921053  0.271448
Third  female  21.750000  12.729964   16.118810  11.690314  0.500000  0.501745