In [2]:
import pandas as pd

In [3]:
dict_data = {
    'c0': [1, 2, 3],
    'c1': [4, 5, 6],
    'c2': [7, 8, 9],
    'c3': [10, 11, 12],
    'c4': [13, 14, 15]
}
df = pd.DataFrame(dict_data)
print(type(df))
print(df)

<class 'pandas.DataFrame'>
   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [4]:
# pandas.DataFrame(2차원배열,
#                  index= 행 인덱스 배열,
#                  columns=열 이름 배열
#                  )
arr = [
    [15, '남', '덕영중'],
    [17, '여', '수리중']
]
df = pd.DataFrame(arr, index=['준서', '예은'], columns=['나이', '성별', '학교'])
print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [5]:
print(list(df.index))
print(list(df.columns))

['준서', '예은']
['나이', '성별', '학교']

In [6]:
# 행 인덱스 변경
# DataFrame객체.index = 행인덱스배열
# DataFrame객체.columns = 열인덱스배열
df.index = ['학생1', '학생2']
print(df)

df.columns = ['연령','남녀','소속']
print(df)

     나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중
     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [7]:
# 행 인덱스 변경 : DataFrame객체.rename(index={기존인덱스: 새인덱스})
# 열 이름 변경 : DataFrame객체.rename(columns={기존이름: 새이름})

import pandas as pd

matrix = [
    [15, '남', '덕영중'],
    [17, '여', '수리중']
]

df = pd.DataFrame(matrix, index=['준서', '예은'], columns=['나이', '성별', '학교'])
df

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [8]:
df = df.rename(columns={
    '나이': '연령',
    '성별': '남여',
    '학교': '소속'
    })                      # 요거는 재할당을 꼭 해줘야 함
df

    연령 남여   소속
준서  15  남  덕영중
예은  17  여  수리중

In [9]:
df = df.rename(index={
    '준서': '학생1',
    '예은': '학생2'
})                           # 요거도 재할당을 꼭 해줘야 함
df

     연령 남여   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [10]:
# 행/열 삭제
# 행 삭제 : DataFrame객체.drop(행인덱스 또는 배열, axis=0, axis='index')
# 열 삭제 : DataFrame객체.drop(열이름 또는 배열, axis=1, axis='columns')

import pandas as pd

exam_data = {
    '수학': [90, 80, 70],
    '영어': [98, 89, 95],
    '음악': [85, 95, 100],
    '체육': [100, 90, 90]
}
df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [11]:
df2 = df.copy()
df2 = df2.drop('우현')
df2

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [12]:
df3 = df.copy()
df3 = df3.drop(['우현', '인아'], axis=0)
df3

    수학  영어  음악   체육
서준  90  98  85  100

In [13]:
df4 = df.copy()
df4 = df4.drop(['우현', '인아'], axis='index')
df4

    수학  영어  음악   체육
서준  90  98  85  100

In [14]:
df5 = df.copy()
df5 = df5.drop(index=['우현'])
df5

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [15]:
import pandas as pd

exam_data = {
    '수학': [90, 80, 70],
    '영어': [98, 89, 95],
    '음악': [85, 95, 100],
    '체육': [100, 90, 90]
}
df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [16]:
df2 = df.copy()
df2 = df2.drop('수학', axis=1)
df2

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

In [17]:
df3 = df.copy()
df3 = df3.drop(['영어', '음악'], axis=1)
df3

    수학   체육
서준  90  100
우현  80   90
인아  70   90

In [18]:
df4 = df.copy()
df4 = df4.drop(['영어', '음악'], axis='columns')
df4

    수학   체육
서준  90  100
우현  80   90
인아  70   90

In [19]:
df5 = df.copy()
df5 = df5.drop(columns=['수학'])
df5

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

In [20]:
# 행 선택
import pandas as pd

exam_data = {
    '수학': [90, 80, 70],
    '영어': [98, 89, 95],
    '음악': [85, 95, 100],
    '체육': [100, 90, 90]
}
df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [21]:
label1 = df.loc['서준']
print(label1)
print(type(label1))

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64
<class 'pandas.Series'>

In [22]:
position1 = df.iloc[0]
print(position1)
print(type(position1))

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64
<class 'pandas.Series'>

In [23]:
label2 = df.loc[['서준', '우현']]
print(label2)
print(type(label2))

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90
<class 'pandas.DataFrame'>

In [24]:
label3 = df.loc[['서준']]
print(label3)
print(type(label3))

    수학  영어  음악   체육
서준  90  98  85  100
<class 'pandas.DataFrame'>

In [25]:
position2 = df.iloc[[0, 1]]
print(position2)
print(type(position2))

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90
<class 'pandas.DataFrame'>

In [26]:
label3 = df.loc['서준':'인아']   # loc는 인덱스 지정된 범위까지 다 가지고 옴
print(label3)
print(type(label3))

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90
<class 'pandas.DataFrame'>

In [27]:
position3 = df.iloc[0:2]    # iloc는 기존의 인덱스 개념과 같이 바로 앞 까지 가지고 옴
print(position3)
print(type(position3))

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90
<class 'pandas.DataFrame'>

In [28]:
# 열 선택
# 열 1개 선택 : DataFrame객체['열이름'] 또는 DataFrame객체.열이름
exam_data = {
    '이름': ['서준', '우현', '인아'],
    '수학': [90, 80, 70],
    '영어': [98, 89, 95],
    '음악': [85, 95, 100],
    '체육': [100, 90, 90]
}
df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [29]:
math1 = df['수학']
math1

0    90
1    80
2    70
Name: 수학, dtype: int64

In [30]:
english = df.영어
english

0    98
1    89
2    95
Name: 영어, dtype: int64

In [31]:
music_gym = df[['음악', '체육']] # 범위가 아니고 각각 가져올 때는 꼭 리스트로 한번 더 감싸줘야함
music_gym

    음악   체육
0   85  100
1   95   90
2  100   90

In [32]:
df[['수학']]

   수학
0  90
1  80
2  70

In [33]:
# 범위 슬라이싱
# 범위 슬라이싱 : DataFrame객체.iloc[시작인덱스:끝인덱스:간격]
df.iloc[::2]

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
2  인아  70  95  100   90

In [34]:
# 원소 선택
# 인덱스이름 : DataFrame객체.loc[행인덱스, 열이름]
# 정수위치인덱스 : DataFrame객체.iloc[행번호, 열번호]

df = df.set_index('이름')
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [35]:
a = df.loc['서준', '음악']
df.iloc[0, 2]

np.int64(85)

In [36]:
df.loc['서준', ['음악', '체육']]

음악     85
체육    100
Name: 서준, dtype: int64

In [37]:
df.iloc[0, [2, 3]]

음악     85
체육    100
Name: 서준, dtype: int64

In [38]:
df.loc['서준', '음악':'체육']

음악     85
체육    100
Name: 서준, dtype: int64

In [39]:
df.iloc[0, 2:]

음악     85
체육    100
Name: 서준, dtype: int64

In [40]:
df.loc[['서준', '우현'], ['음악', '체육']]

    음악   체육
이름
서준  85  100
우현  95   90

In [41]:
df.iloc[[0, 1], [2, 3]]

    음악   체육
이름
서준  85  100
우현  95   90

In [42]:
df.loc['서준':'우현', '음악':'체육']

    음악   체육
이름
서준  85  100
우현  95   90

In [43]:
df.iloc[0:2, 2:]

    음악   체육
이름
서준  85  100
우현  95   90

In [44]:
# 열 추가
# 열추가: DataFrame객체['추가하려는 열 이름'] = 데이터값

exam_data = {
    '이름': ['서준', '우현', '인아'],
    '수학': [90, 80, 70],
    '영어': [98, 89, 95],
    '음악': [85, 95, 100],
    '체육': [100, 90, 90]
}
df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [45]:
df['국어'] = 80
df

   이름  수학  영어   음악   체육  국어
0  서준  90  98   85  100  80
1  우현  80  89   95   90  80
2  인아  70  95  100   90  80

In [46]:
df['미술'] = [80, 90, 100]
df

   이름  수학  영어   음악   체육  국어   미술
0  서준  90  98   85  100  80   80
1  우현  80  89   95   90  80   90
2  인아  70  95  100   90  80  100

In [47]:
# 행추가
# 행추가: DataFrame객체.loc['새로운행 이름'] = 데이터값 또는 배열

exam_data = {
    '이름': ['서준', '우현', '인아'],
    '수학': [90, 80, 70],
    '영어': [98, 89, 95],
    '음악': [85, 95, 100],
    '체육': [100, 90, 90]
}
df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [48]:
print(df.loc[0:2])
print(df.iloc[0:2])

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
   이름  수학  영어  음악   체육
0  서준  90  98  85  100
1  우현  80  89  95   90

In [49]:
df.loc[3] = 0
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
3   0   0   0    0    0

In [50]:
df.loc[4] = ['동규', 90, 80, 70, 60]
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
3   0   0   0    0    0
4  동규  90  80   70   60

In [51]:
df.loc['행5'] = df.loc[3]
df

    이름  수학  영어   음악   체육
0   서준  90  98   85  100
1   우현  80  89   95   90
2   인아  70  95  100   90
3    0   0   0    0    0
4   동규  90  80   70   60
행5   0   0   0    0    0

In [2]:
# 원소 값 변경
import pandas as pd

exam_data = {
    '이름': ['서준', '우현', '인아'],
    '수학': [90, 80, 70],
    '영어': [98, 89, 95],
    '음악': [85, 95, 100],
    '체육': [100, 90, 90]
}
df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [4]:
df = df.set_index('이름')
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [6]:
df.iloc[0, 3] = 80
df

    수학  영어   음악  체육
이름
서준  90  98   85  80
우현  80  89   95  90
인아  70  95  100  90

In [10]:
df.loc['서준', '체육'] = 90

In [11]:
df

    수학  영어   음악  체육
이름
서준  90  98   85  90
우현  80  89   95  90
인아  70  95  100  90

In [13]:
df.loc['서준', ['음악', '체육']] = 90
df

    수학  영어   음악  체육
이름
서준  90  98   90  90
우현  80  89   95  90
인아  70  95  100  90

In [ ]:
df.loc['서준', ['음악', '체육']] = 100, 50
df

    수학  영어   음악  체육
이름
서준  90  98  100  50
우현  80  89   95  90
인아  70  95  100  90

In [15]:
# 행과 열의 위치 바꾸기
# 행, 열 바꾸기 : DataFrame객체.transpose() 또는 T

import pandas as pd

exam_data = {
    '이름': ['서준', '우현', '인아'],
    '수학': [90, 80, 70],
    '영어': [98, 89, 95],
    '음악': [85, 95, 100],
    '체육': [100, 90, 90]
}
df = pd.DataFrame(exam_data)
df

df = df.transpose()
df

      0   1    2
이름   서준  우현   인아
수학   90  80   70
영어   98  89   95
음악   85  95  100
체육  100  90   90

In [16]:
df = df.T
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90